# Práctica 1: Data Cleaning

## Objetivo
Realizar la limpieza de datos de un conjunto de datos seleccionado (EPL 2024-2025 Match Shots) para asegurar su calidad y preparar el dataset para análisis posteriores.

## Requisitos del Dataset
- Al menos 5000 filas.
- Al menos 4 variables.
- Al menos 2 variables numéricas.
- Al menos 1 variable alfanumérica.
- Al menos 1 variable de fecha.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json

# Configuración de visualización
%matplotlib inline
sns.set(style="whitegrid")

## 1. Carga de Datos
Cargamos el dataset `epl_2024_2025_match_shots.csv` y realizamos una inspección inicial.

In [2]:
# Cargar el dataset
try:
    df = pd.read_csv('/Users/diegoandre/SEMESTRE 7/MINERIA DE DATOS/premierleague-datamining/epl_2024_2025_match_shots.csv')
    print("Dataset cargado exitosamente.")
except FileNotFoundError:
    print("El archivo no se encuentra. Verifica la ruta.")

# Mostrar las primeras filas
df.head()

Dataset cargado exitosamente.

,player,isHome,shotType,situation,playerCoordinates,bodyPart,goalMouthLocation,goalMouthCoordinates,blockCoordinates,xg,...,addedTime,timeSeconds,draw,reversedPeriodTime,reversedPeriodTimeSeconds,periodTimeSeconds,incidentType,goalType,match_id,match_date
0,"{""name"": ""Jean-Philippe Mateta"", ""slug"": ""jean...",False,block,assisted,"{""x"": 19.8, ""y"": 37.6, ""z"": 0}",left-foot,low-centre,"{""x"": 0, ""y"": 50.1, ""z"": 19}","{""x"": 16.7, ""y"": 39.5, ""z"": 0}",0.044247,...,NaN,18,"{""start"": {""x"": 37.6, ""y"": 19.8}, ""block"": {""x...",45,2682,18,shot,NaN,12436910,2024-09-01
1,"{""name"": ""Jaden Philogene-Bidace"", ""slug"": ""ja...",True,block,assisted,"{""x"": 7.6, ""y"": 60.1, ""z"": 0}",right-foot,low-centre,"{""x"": 0, ""y"": 49.5, ""z"": 19}","{""x"": 0.90000000000001, ""y"": 51.6, ""z"": 0}",0.137589,...,NaN,24,"{""start"": {""x"": 60.1, ""y"": 7.6}, ""block"": {""x""...",45,2676,24,shot,NaN,12436629,2025-02-22
2,"{""name"": ""Harvey Barnes"", ""firstName"": """", ""la...",True,block,assisted,"{""x"": 20.6, ""y"": 48.7, ""z"": 0}",right-foot,low-left,"{""x"": 0, ""y"": 52.2, ""z"": 19}","{""x"": 13.1, ""y"": 48.4, ""z"": 0}",0.034956,...,NaN,25,"{""start"": {""x"": 48.7, ""y"": 20.6}, ""block"": {""x...",45,2675,25,shot,NaN,12436999,NaN
3,"{""name"": ""Conor Chaplin"", ""firstName"": """", ""la...",True,block,throw-in-set-piece,"{""x"": 14.1, ""y"": 50.3, ""z"": 0}",left-foot,low-centre,"{""x"": 0, ""y"": 50.7, ""z"": 19}","{""x"": 12.4, ""y"": 50.2, ""z"": 0}",0.052231,...,NaN,32,"{""start"": {""x"": 50.3, ""y"": 14.1}, ""block"": {""x...",45,2668,32,shot,NaN,12436538,2025-05-25
4,"{""name"": ""Marcus Rashford"", ""slug"": ""marcus-ra...",False,block,assisted,"{""x"": 14.1, ""y"": 72.9, ""z"": 0}",right-foot,low-centre,"{""x"": 0, ""y"": 51.4, ""z"": 19}","{""x"": 12, ""y"": 69.3, ""z"": 0}",0.047109,...,NaN,33,"{""start"": {""x"": 72.9, ""y"": 14.1}, ""block"": {""x...",45,2667,33,shot,NaN,12436614,2025-04-12

## 2. Exploración Inicial
Revisamos la estructura del dataset, tipos de datos y valores nulos.

In [3]:
# Información general del dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8746 entries, 0 to 8745
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   player                     8746 non-null   object
 1   isHome                     8746 non-null   bool
 2   shotType                   8746 non-null   object
 3   situation                  8746 non-null   object
 4   playerCoordinates          8746 non-null   object
 5   bodyPart                   8746 non-null   object
 6   goalMouthLocation          8746 non-null   object
 7   goalMouthCoordinates       8746 non-null   object
 8   blockCoordinates           5122 non-null   object
 9   xg                         8717 non-null   float64
 10  xgot                       8720 non-null   float64
 11  id                         8746 non-null   int64
 12  time                       8746 non-null   int64
 13  addedTime                  936 non-null    float64
 14  timeSeconds                8746 non-null   int64
 15  draw                       8746 non-null   object
 16  reversedPeriodTime         8746 non-null   int64
 17  reversedPeriodTimeSeconds  8746 non-null   int64
 18  periodTimeSeconds          8746 non-null   int64
 19  incidentType               8746 non-null   object
 20  goalType                   963 non-null    object
 21  match_id                   8746 non-null   int64
 22  match_date                 7987 non-null   object
dtypes: bool(1), float64(3), int64(7), object(12)
memory usage: 1.5+ MB

In [4]:
# Estadísticas descriptivas de variables numéricas
df.describe()

,xg,xgot,id,time,addedTime,timeSeconds,reversedPeriodTime,reversedPeriodTimeSeconds,periodTimeSeconds,match_id
count,8717.000000,8720.000000,8.746000e+03,8746.000000,936.000000,8746.000000,8746.000000,8746.000000,8746.000000,8.746000e+03
mean,0.110603,0.111221,4.294593e+06,49.652298,3.679487,2971.935170,20.324377,1320.095472,1245.923279,1.245188e+07
std,0.145585,0.227682,3.825088e+05,26.637815,2.273739,1626.368225,13.746761,775.188783,809.206987,1.256771e+05
min,0.002711,0.000000,3.605351e+06,1.000000,1.000000,10.000000,1.000000,0.000000,1.000000,1.243641e+07
25%,0.030832,0.000000,4.011986e+06,27.000000,2.000000,1602.000000,8.000000,664.000000,492.000000,1.243652e+07
50%,0.056940,0.000000,4.208022e+06,49.000000,3.000000,2956.000000,20.000000,1268.000000,1214.500000,1.243662e+07
75%,0.121499,0.097146,4.589997e+06,73.000000,5.000000,4326.750000,32.000000,1999.000000,1956.000000,1.243697e+07
max,0.984898,0.995510,5.006757e+06,90.000000,13.000000,6176.000000,45.000000,2698.000000,2700.000000,1.385459e+07

In [5]:
# Conteo de valores nulos por columna
df.isnull().sum()

player                          0
isHome                          0
shotType                        0
situation                       0
playerCoordinates               0
bodyPart                        0
goalMouthLocation               0
goalMouthCoordinates            0
blockCoordinates             3624
xg                             29
xgot                           26
id                              0
time                            0
addedTime                    7810
timeSeconds                     0
draw                            0
reversedPeriodTime              0
reversedPeriodTimeSeconds       0
periodTimeSeconds               0
incidentType                    0
goalType                     7783
match_id                        0
match_date                    759
dtype: int64

## 3. Limpieza de Datos

### 3.1. Manejo de Columnas JSON
La columna `player` y `playerCoordinates` contienen datos en formato JSON. Necesitamos extraer la información relevante.

In [6]:
def parse_json_column(df, column_name, keys_to_extract):
    """
    Parsea una columna con strings JSON y extrae claves específicas.
    """
    extracted_data = []
    for item in df[column_name]:
        try:
            # Reemplazar comillas dobles escapadas si es necesario (depende del formato CSV)
            # En este caso, pandas suele manejar el CSV, pero el contenido puede ser un string JSON
            if isinstance(item, str):
                data = json.loads(item)
            else:
                data = {}
            
            extracted_row = {key: data.get(key, np.nan) for key in keys_to_extract}
            extracted_data.append(extracted_row)
        except json.JSONDecodeError:
            extracted_data.append({key: np.nan for key in keys_to_extract})
            
    return pd.DataFrame(extracted_data)

# Extraer datos de 'player'
player_keys = ['name', 'position', 'id']
player_data = parse_json_column(df, 'player', player_keys)
player_data.columns = ['player_name', 'player_position', 'player_id']

# Unir al dataframe original
df = pd.concat([df, player_data], axis=1)

# Mostrar resultado parcial
df[['player', 'player_name', 'player_position']].head()

,player,player_name,player_position
0,"{""name"": ""Jean-Philippe Mateta"", ""slug"": ""jean...",Jean-Philippe Mateta,F
1,"{""name"": ""Jaden Philogene-Bidace"", ""slug"": ""ja...",Jaden Philogene-Bidace,M
2,"{""name"": ""Harvey Barnes"", ""firstName"": """", ""la...",Harvey Barnes,F
3,"{""name"": ""Conor Chaplin"", ""firstName"": """", ""la...",Conor Chaplin,M
4,"{""name"": ""Marcus Rashford"", ""slug"": ""marcus-ra...",Marcus Rashford,M

In [7]:
# Extraer datos de 'playerCoordinates'
coords_keys = ['x', 'y']
coords_data = parse_json_column(df, 'playerCoordinates', coords_keys)
coords_data.columns = ['shot_x', 'shot_y']

# Unir al dataframe original
df = pd.concat([df, coords_data], axis=1)

# Eliminar columnas JSON originales para limpiar
df.drop(columns=['player', 'playerCoordinates'], inplace=True)

df.head()

,isHome,shotType,situation,bodyPart,goalMouthLocation,goalMouthCoordinates,blockCoordinates,xg,xgot,id,...,periodTimeSeconds,incidentType,goalType,match_id,match_date,player_name,player_position,player_id,shot_x,shot_y
0,False,block,assisted,left-foot,low-centre,"{""x"": 0, ""y"": 50.1, ""z"": 19}","{""x"": 16.7, ""y"": 39.5, ""z"": 0}",0.044247,0.0,3701430,...,18,shot,NaN,12436910,2024-09-01,Jean-Philippe Mateta,F,848276,19.8,37.6
1,True,block,assisted,right-foot,low-centre,"{""x"": 0, ""y"": 49.5, ""z"": 19}","{""x"": 0.90000000000001, ""y"": 51.6, ""z"": 0}",0.137589,0.0,4475948,...,24,shot,NaN,12436629,2025-02-22,Jaden Philogene-Bidace,M,1014461,7.6,60.1
2,True,block,assisted,right-foot,low-left,"{""x"": 0, ""y"": 52.2, ""z"": 19}","{""x"": 13.1, ""y"": 48.4, ""z"": 0}",0.034956,0.0,3832216,...,25,shot,NaN,12436999,NaN,Harvey Barnes,F,855647,20.6,48.7
3,True,block,throw-in-set-piece,left-foot,low-centre,"{""x"": 0, ""y"": 50.7, ""z"": 19}","{""x"": 12.4, ""y"": 50.2, ""z"": 0}",0.052231,0.0,5000250,...,32,shot,NaN,12436538,2025-05-25,Conor Chaplin,M,784625,14.1,50.3
4,False,block,assisted,right-foot,low-centre,"{""x"": 0, ""y"": 51.4, ""z"": 19}","{""x"": 12, ""y"": 69.3, ""z"": 0}",0.047109,0.0,4742872,...,33,shot,NaN,12436614,2025-04-12,Marcus Rashford,M,814590,14.1,72.9

### 3.2. Conversión de Tipos de Datos
Aseguramos que `match_date` sea de tipo datetime.

In [8]:
# Convertir match_date a datetime
df['match_date'] = pd.to_datetime(df['match_date'], errors='coerce')

# Verificar conversión
print(df['match_date'].dtype)

# Verificar si hay fechas nulas después de la conversión
missing_dates = df['match_date'].isnull().sum()
print(f"Fechas faltantes: {missing_dates}")

datetime64[ns]
Fechas faltantes: 759

### 3.3. Manejo de Valores Nulos
Decidimos qué hacer con los valores nulos encontrados.

In [9]:
# Eliminar filas donde la fecha del partido sea nula (requisito crítico)
df_cleaned = df.dropna(subset=['match_date'])

# Verificar el tamaño del dataset después de eliminar nulos
print(f"Filas originales: {len(df)}")
print(f"Filas después de limpieza: {len(df_cleaned)}")

Filas originales: 8746
Filas después de limpieza: 7987

### 3.4. Eliminación de Duplicados
Verificamos si existen registros duplicados.

In [10]:
duplicates = df_cleaned.duplicated().sum()
print(f"Duplicados encontrados: {duplicates}")

if duplicates > 0:
    df_cleaned = df_cleaned.drop_duplicates()
    print("Duplicados eliminados.")

Duplicados encontrados: 0

## 4. Validación Final
Revisamos el dataset limpio antes de guardarlo.

In [11]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7987 entries, 0 to 8745
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   isHome                     7987 non-null   bool
 1   shotType                   7987 non-null   object
 2   situation                  7987 non-null   object
 3   bodyPart                   7987 non-null   object
 4   goalMouthLocation          7987 non-null   object
 5   goalMouthCoordinates       7987 non-null   object
 6   blockCoordinates           4669 non-null   object
 7   xg                         7960 non-null   float64
 8   xgot                       7963 non-null   float64
 9   id                         7987 non-null   int64
 10  time                       7987 non-null   int64
 11  addedTime                  857 non-null    float64
 12  timeSeconds                7987 non-null   int64
 13  draw                       7987 non-null   object
 14  reversedPeriodTime         7987 non-null   int64
 15  reversedPeriodTimeSeconds  7987 non-null   int64
 16  periodTimeSeconds          7987 non-null   int64
 17  incidentType               7987 non-null   object
 18  goalType                   884 non-null    object
 19  match_id                   7987 non-null   int64
 20  match_date                 7987 non-null   datetime64[ns]
 21  player_name                7987 non-null   object
 22  player_position            7987 non-null   object
 23  player_id                  7987 non-null   int64
 24  shot_x                     7987 non-null   float64
 25  shot_y                     7987 non-null   float64
dtypes: bool(1), datetime64[ns](1), float64(5), int64(8), object(11)
memory usage: 1.6+ MB

In [12]:
df_cleaned.head()

,isHome,shotType,situation,bodyPart,goalMouthLocation,goalMouthCoordinates,blockCoordinates,xg,xgot,id,...,periodTimeSeconds,incidentType,goalType,match_id,match_date,player_name,player_position,player_id,shot_x,shot_y
0,False,block,assisted,left-foot,low-centre,"{""x"": 0, ""y"": 50.1, ""z"": 19}","{""x"": 16.7, ""y"": 39.5, ""z"": 0}",0.044247,0.0,3701430,...,18,shot,NaN,12436910,2024-09-01,Jean-Philippe Mateta,F,848276,19.8,37.6
1,True,block,assisted,right-foot,low-centre,"{""x"": 0, ""y"": 49.5, ""z"": 19}","{""x"": 0.90000000000001, ""y"": 51.6, ""z"": 0}",0.137589,0.0,4475948,...,24,shot,NaN,12436629,2025-02-22,Jaden Philogene-Bidace,M,1014461,7.6,60.1
3,True,block,throw-in-set-piece,left-foot,low-centre,"{""x"": 0, ""y"": 50.7, ""z"": 19}","{""x"": 12.4, ""y"": 50.2, ""z"": 0}",0.052231,0.0,5000250,...,32,shot,NaN,12436538,2025-05-25,Conor Chaplin,M,784625,14.1,50.3
4,False,block,assisted,right-foot,low-centre,"{""x"": 0, ""y"": 51.4, ""z"": 19}","{""x"": 12, ""y"": 69.3, ""z"": 0}",0.047109,0.0,4742872,...,33,shot,NaN,12436614,2025-04-12,Marcus Rashford,M,814590,14.1,72.9
5,True,block,regular,right-foot,low-centre,"{""x"": 0, ""y"": 48.9, ""z"": 19}","{""x"": 13.7, ""y"": 48.7, ""z"": 0}",0.066052,0.0,4202996,...,33,shot,NaN,12436532,2024-12-29,Eberechi Eze,F,864921,15.1,48.5

## 5. Guardado de Datos
Guardamos el dataset limpio en un nuevo archivo CSV.

In [13]:
df_cleaned.to_csv('cleaned_epl_shots.csv', index=False)
print("Archivo guardado como 'cleaned_epl_shots.csv'")

Archivo guardado como 'cleaned_epl_shots.csv'